<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="8047" started-at="2019-12-25T04:22:49Z" finished-at="2019-12-25T04:22:57Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="8047" started-at="2019-12-25T04:22:49Z" finished-at="2019-12-25T04:22:57Z">
      <class name="pack1.Program1">
        <test-method status="FAIL" signature="main()[pri:0, instance:pack1.Program1@68be2bc2]" name="main" duration-ms="8009" started-at="2019-12-25T09:52:49Z" finished-at="2019-12-25T09:52:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	orange hrm page not found expected [OrangeHRM] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	orange hrm page not found expected [OrangeHRM] but found []
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at pack1.Program1.main(Program1.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
        <test-method status="PASS" signature="main1()[pri:0, instance:pack1.Program1@68be2bc2]" name="main1" duration-ms="0" started-at="2019-12-25T09:52:57Z" finished-at="2019-12-25T09:52:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main1 -->
      </class> <!-- pack1.Program1 -->
      <class name="pack1.TestNgPractice">
        <test-method status="PASS" signature="m1()[pri:0, instance:pack1.TestNgPractice@2a2d45ba]" name="m1" duration-ms="16" started-at="2019-12-25T09:52:49Z" finished-at="2019-12-25T09:52:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m1 -->
        <test-method status="PASS" signature="m2()[pri:0, instance:pack1.TestNgPractice@2a2d45ba]" name="m2" duration-ms="0" started-at="2019-12-25T09:52:49Z" finished-at="2019-12-25T09:52:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m2 -->
      </class> <!-- pack1.TestNgPractice -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
